# Generated by Django 5.2.7 on 2025-10-16 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0009_alter_animalgenus_options_alter_pet_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Номер сертификата')),
                ('certificate_type', models.CharField(choices=[('vaccination', 'Вакцинация'), ('sterilization', 'Стерилизация'), ('pedigree', 'Родословная'), ('training', 'Тренировка / курс'), ('other', 'Прочее')], max_length=50, verbose_name='Тип сертификата')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название документа')),
                ('issue_date', models.DateField(auto_now_add=True, null=True, verbose_name='Дата выдачи')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='Срок действия')),
                ('issued_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='Кем выдан')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание / комментарий')),
                ('document_file', models.FileField(blank=True, null=True, upload_to='pets/certificates/', verbose_name='Файл сертификата')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='pets.pet', verbose_name='Питомец')),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
                'db_table': 'certificate',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='MedicalCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_number', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Номер медкарты')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Вес (кг)')),
                ('blood_type', models.CharField(blank=True, max_length=10, null=True, verbose_name='Группа крови')),
                ('allergies', models.TextField(blank=True, null=True, verbose_name='Аллергии')),
                ('chronic_diseases', models.TextField(blank=True, null=True, verbose_name='Хронические заболевания')),
                ('vaccinations', models.TextField(blank=True, null=True, verbose_name='Прививки (описание)')),
                ('last_checkup_date', models.DateField(blank=True, null=True, verbose_name='Последний осмотр')),
                ('next_checkup_date', models.DateField(blank=True, null=True, verbose_name='Следующий осмотр')),
                ('certificate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_cards', to='pets_documents.certificate', verbose_name='Связанный сертификат')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_cards', to='pets.pet', verbose_name='Питомец')),
            ],
            options={
                'verbose_name': 'Медицинская карта',
                'verbose_name_plural': 'Медицинские карты',
                'db_table': 'medical_card',
            },
        ),
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_number', models.CharField(max_length=50, unique=True, verbose_name='Номер паспорта')),
                ('issue_date', models.DateField(auto_now_add=True, verbose_name='Дата выдачи')),
                ('issued_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='Кем выдан')),
                ('microchip_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер микрочипа')),
                ('country_of_issue', models.CharField(blank=True, max_length=100, null=True, verbose_name='Страна выдачи')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='pets/passports/', verbose_name='Фото паспорта')),
                ('pet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='passport', to='pets.pet', verbose_name='Питомец')),
            ],
            options={
                'verbose_name': 'Паспорт питомца',
                'verbose_name_plural': 'Паспорта питомцев',
                'db_table': 'passport',
                'ordering': ['-issue_date'],
            },
        ),
    ]
