# Generated by Django 5.2.7 on 2025-10-19 08:05

import pets_documents.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets_documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='document_file',
            field=models.FileField(blank=True, null=True, storage=pets_documents.storage.PetFileImageStorage(), upload_to=pets_documents.storage.PetFileImageStorage.image_path, verbose_name='Файл сертификата'),
        ),
    ]
