# Generated by Django 5.2.7 on 2025-10-27 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vet_clinics', '0003_treatment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='clinic',
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=8, verbose_name='Цена по умолчанию'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='cost',
            field=models.DecimalField(decimal_places=0, max_digits=8, verbose_name='Стоимость'),
        ),
        migrations.CreateModel(
            name='ClinicService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_override', models.DecimalField(blank=True, decimal_places=0, max_digits=8, null=True, verbose_name='Цена в этой клинике (если отличается)')),
                ('available', models.BooleanField(default=True, verbose_name='Доступна')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_services', to='vet_clinics.clinic', verbose_name='Клиника')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_services', to='vet_clinics.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Услуга клиники',
                'verbose_name_plural': 'Услуги клиник',
                'db_table': '"vet_clinics"."clinic_service"',
                'unique_together': {('clinic', 'service')},
            },
        ),
        migrations.AddField(
            model_name='clinic',
            name='services',
            field=models.ManyToManyField(related_name='clinics', through='vet_clinics.ClinicService', to='vet_clinics.service', verbose_name='Предоставляемые услуги'),
        ),
    ]
