# Generated by Django 5.2.7 on 2025-11-07 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vet_clinics', '0004_remove_service_clinic_alter_service_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Долгота'),
        ),
    ]
