# Generated by Django 5.2.7 on 2025-10-21 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0002_initial"),
        ("vet_clinics", "0002_appointment_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Treatment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("diagnosis", models.TextField(verbose_name="Диагноз")),
                ("procedure", models.TextField(verbose_name="Проведённая процедура")),
                ("cost", models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Стоимость")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="treatments",
                        to="vet_clinics.appointment",
                        verbose_name="Запись на приём",
                    ),
                ),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="treatments",
                        to="pets.pet",
                        verbose_name="Питомец",
                    ),
                ),
                (
                    "veterinarian",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="treatments",
                        to="vet_clinics.veterinarian",
                        verbose_name="Ветеринар",
                    ),
                ),
            ],
            options={
                "db_table": '"vet_clinics"."treatment"',
                "verbose_name": "Лечебная процедура",
                "verbose_name_plural": "Лечебные процедуры",
                "ordering": ["-created_at"],
            },
        ),
    ]
