# Generated by Django 5.2.7 on 2025-10-13 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animalcategory',
            options={'verbose_name': 'Категория животных', 'verbose_name_plural': 'Категории животных'},
        ),
        migrations.AlterModelOptions(
            name='pet',
            options={'verbose_name': 'Питомец', 'verbose_name_plural': 'Питомцы'},
        ),
        migrations.AlterModelOptions(
            name='species',
            options={'verbose_name': 'Порода', 'verbose_name_plural': 'Породы'},
        ),
        migrations.AlterModelOptions(
            name='userpet',
            options={'verbose_name': 'Питомец пользователя', 'verbose_name_plural': 'Питомцы пользователей'},
        ),
        migrations.AlterModelTable(
            name='animalcategory',
            table='animal_categories',
        ),
        migrations.AlterModelTable(
            name='pet',
            table='pets',
        ),
        migrations.AlterModelTable(
            name='species',
            table='species',
        ),
    ]
