# Generated by Django 5.2.7 on 2025-10-25 14:11

import django.db.models.deletion
import pets.storage
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='species',
            name='category',
        ),
        migrations.AddField(
            model_name='species',
            name='genus',
            field=models.ForeignKey(default=1, help_text='К какому роду относится порода', on_delete=django.db.models.deletion.CASCADE, to='pets.animalgenus', verbose_name='Род животных'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='animalgenus',
            name='name',
            field=models.CharField(help_text="Название рода животных (например, 'Кошки', 'Собаки')", max_length=100, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='birth_date',
            field=models.DateField(blank=True, help_text='Дата рождения питомца', null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Мужской'), ('F', 'Женский')], help_text='Пол питомца', max_length=1, null=True, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='genus',
            field=models.ForeignKey(blank=True, help_text='К какому роду относится питомец', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pets.animalgenus', verbose_name='Род животного'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='image',
            field=models.ImageField(blank=True, help_text='Фотография питомца', null=True, storage=pets.storage.PetImageStorage(), upload_to=pets.storage.PetImageStorage.image_path, verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='name',
            field=models.CharField(help_text='Кличка питомца', max_length=100, verbose_name='Кличка'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='species',
            field=models.ForeignKey(blank=True, help_text='Порода питомца', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pets.species', verbose_name='Порода'),
        ),
        migrations.AlterField(
            model_name='species',
            name='name',
            field=models.CharField(help_text='Название породы животного', max_length=100, verbose_name='Название породы'),
        ),
        migrations.AlterField(
            model_name='userpet',
            name='pet',
            field=models.ForeignKey(help_text='Питомец, принадлежащий пользователю', on_delete=django.db.models.deletion.CASCADE, to='pets.pet', verbose_name='Питомец'),
        ),
        migrations.AlterField(
            model_name='userpet',
            name='user',
            field=models.ForeignKey(help_text='Владелец питомца', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
