# Generated by Django 5.2.7 on 2025-10-14 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_alter_animalcategory_options_alter_pet_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpet',
            name='added_at',
        ),
    ]
