# Generated by Django 5.2.7 on 2025-10-14 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_remove_userpet_added_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='gender',
            field=models.CharField(blank=True, choices=[('S', 'Сука'), ('K', 'Кабель')], max_length=10, null=True),
        ),
    ]
