# Generated by Django 5.2.7 on 2025-10-15 13:33

import pets.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_alter_pet_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Женский'), ('F', 'Мужской')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=pets.storage.PetImageStorage(), upload_to=pets.storage.PetImageStorage.image_path, verbose_name='Аватар'),
        ),
    ]
