# Generated by Django 5.2.7 on 2025-10-15 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0006_alter_pet_gender_alter_pet_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='description',
        ),
        migrations.AddField(
            model_name='pet',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pets.animalcategory'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pets.species'),
        ),
    ]
