# Generated by Django 5.2.7 on 2025-10-15 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0007_remove_pet_description_pet_category_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AnimalCategory',
            new_name='AnimalGenus',
        ),
        migrations.RenameField(
            model_name='pet',
            old_name='category',
            new_name='genus',
        ),
    ]
