# Generated by Django 5.2.7 on 2025-10-16 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0008_rename_animalcategory_animalgenus_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animalgenus',
            options={'verbose_name': 'Род животных', 'verbose_name_plural': 'Категории животных'},
        ),
        migrations.AlterField(
            model_name='pet',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=1, null=True),
        ),
    ]
