# Generated by Django 5.2.7 on 2025-10-25 14:11

import users.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_remove_species_category_species_genus_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Email пользователя. Используется для входа в систему.', max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, help_text='Фотография или аватар пользователя.', null=True, storage=users.storage.UserImageStorage(), upload_to=users.storage.UserImageStorage.image_path, verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pets',
            field=models.ManyToManyField(help_text='Питомцы, связанные с пользователем.', related_name='owners', through='pets.UserPet', to='pets.pet', verbose_name='Питомцы'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Контактный номер телефона пользователя.', max_length=20, null=True, unique=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(default='user', help_text='Роль пользователя в системе (user, vet, admin).', max_length=50, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, help_text='Необязательное поле. Может использоваться для отображения.', max_length=150, null=True, unique=True, verbose_name='Имя пользователя'),
        ),
    ]
